<?php

namespace CLM\MfrBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BrokerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrokerRepository extends EntityRepository
{
}
